'''
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register('todo', views.TodoViewSet, basename='todo')

urlpatterns = [
]

urlpatterns += router.urls
'''



from django.urls import path, include
from rest_framework import routers
from .views import TodoViewSet, TransactionHistoryViewSet

router = routers.DefaultRouter()
router.register('todo', TodoViewSet, basename='todo')
router.register('transactions', TransactionHistoryViewSet, basename='transactions')

urlpatterns = [
    path('', include(router.urls)),
]

'''
from django.urls import path, include
from rest_framework import routers
from .views import TodoViewSet, TransactionHistoryViewSet  # Import the necessary viewsets

# Create a router instance
router = routers.DefaultRouter()

# Register the viewsets with the router
router.register('todo', TodoViewSet, basename='todo')  # Register Todo viewset
router.register('transactions', TransactionHistoryViewSet, basename='transactions')  # Register TransactionHistory viewset

# Define the URL patterns to include the router's URLs
urlpatterns = [
    path('', include(router.urls)),  # Include the URL patterns generated by the router
]

'''
