# Generated by Django 5.1.5 on 2025-03-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('completed', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('Beverage', 'Beverage'), ('Fruits', 'Fruits'), ('Non-Perishable Item', 'Non-Perishable Item')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Added', 'Added'), ('Updated', 'Updated'), ('Deleted', 'Deleted'), ('Stock-Out', 'Stock-Out'), ('Stock-In', 'Stock-In')], max_length=10)),
                ('item_name', models.CharField(max_length=300)),
                ('quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('previous_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_out_quantity', models.IntegerField(blank=True, null=True)),
                ('stock_in_quantity', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
