# Generated by Django 5.1.5 on 2025-01-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
