# Generated by Django 5.1.5 on 2025-03-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
