# Generated by Django 5.1.5 on 2025-01-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_quantity_todo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
