# Generated by Django 5.1.5 on 2025-03-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
