# Generated by Django 5.1.5 on 2025-01-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
