# Generated by Django 5.1.5 on 2025-03-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_booking_unavailabledate_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10),
        ),
    ]
