# Generated by Django 5.1.5 on 2025-01-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='type',
            field=models.CharField(blank=True, choices=[('Beverage', 'Beverage'), ('Fruits', 'Fruits'), ('Non-Perishable', 'Non-Perishable Item')], max_length=100, null=True),
        ),
    ]
