# Generated by Django 5.1.5 on 2025-04-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_drinkcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_pax', models.IntegerField()),
                ('product_name', models.CharField(max_length=100)),
                ('quantity_per_pax', models.IntegerField()),
            ],
        ),
    ]
