# Generated by Django 5.1.5 on 2025-04-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_productallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
