# Generated by Django 5.1.5 on 2025-02-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_alter_transactionhistory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
