# Generated by Django 5.1.5 on 2025-04-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_remove_transactionhistory_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='action',
            field=models.CharField(choices=[('Added', 'Added'), ('Updated', 'Updated'), ('Deleted', 'Deleted'), ('Stock-Out', 'Stock-Out'), ('Stock-In', 'Stock-In'), ('Stock-Out (Event)', 'Stock-Out (Event)')], max_length=20),
        ),
    ]
