# Generated by Django 5.1.5 on 2025-04-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_transactionhistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='action',
            field=models.CharField(choices=[('Added', 'Added'), ('Updated', 'Updated'), ('Deleted', 'Deleted'), ('Stock-Out', 'Stock-Out'), ('Stock-In', 'Stock-In')], max_length=10),
        ),
    ]
