# Generated by Django 5.1.5 on 2025-04-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_alter_transactionhistory_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
