# Generated by Django 5.1.5 on 2025-04-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_transactionhistory_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
