# Generated by Django 5.1.5 on 2025-02-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_alter_transactionhistory_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
