# Generated by Django 5.1.5 on 2025-02-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_alter_transactionhistory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='stock_out_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='action',
            field=models.CharField(choices=[('Added', 'Added'), ('Updated', 'Updated'), ('Deleted', 'Deleted'), ('Stock-Out', 'Stock-Out')], max_length=10),
        ),
    ]
