# Generated by Django 5.1.5 on 2025-02-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_transactionhistory_stock_out_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='stock_in_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='action',
            field=models.CharField(choices=[('Added', 'Added'), ('Updated', 'Updated'), ('Deleted', 'Deleted'), ('Stock-Out', 'Stock-Out'), ('Stock-In', 'Stock-In')], max_length=10),
        ),
    ]
