# Generated by Django 5.1.5 on 2025-04-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_alter_todo_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='volume',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
