# Generated by Django 5.1.5 on 2025-04-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_alter_todo_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
