# Generated by Django 5.1.5 on 2025-02-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_transactionhistory_previous_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('preparation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
