# Generated by Django 5.1.5 on 2025-04-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_alter_todo_volume'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionhistory',
            unique_together={('action', 'item_name', 'quantity', 'type', 'volume')},
        ),
    ]
