# Generated by Django 5.1.5 on 2025-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparation',
            name='preparation_date',
            field=models.DateField(),
        ),
    ]
