# Generated by Django 5.1.5 on 2025-05-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_alter_transactionhistory_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionhistory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='action',
            field=models.CharField(choices=[('Added', 'Added'), ('Updated', 'Updated'), ('Deleted', 'Deleted'), ('Stock-Out', 'Stock-Out'), ('Stock-In', 'Stock-In')], max_length=50),
        ),
    ]
