# Generated by Django 5.1.5 on 2026-03-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_alter_transactionhistory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
