# Generated by Django 5.1.5 on 2026-03-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_alter_booking_pax'),
    ]

    operations = [
    ]
