# Generated by Django 5.1.5 on 2026-03-23 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0023_postransaction_postransactionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='positem',
            name='deduct_per_sale',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='positem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_items', to='todo.todo'),
        ),
    ]
