# Generated by Django 5.1.5 on 2026-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0023_auto_20260324_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='pax',
        ),
        migrations.AlterField(
            model_name='productallocation',
            name='package_pax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productallocation',
            name='quantity_per_pax',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
