# Generated by Django 5.1.5 on 2026-03-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0024_positem_deduct_per_sale_positem_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='num_pax',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='num_seniors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='senior_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
