# Generated by Django 5.1.5 on 2026-03-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0025_postransaction_num_pax_postransaction_num_seniors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='voided_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
