# Generated by Django 5.1.5 on 2026-03-24 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_postransaction_voided_postransaction_voided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='payment_method',
            field=models.CharField(default='cash', max_length=20),
        ),
    ]
