# Generated by Django 5.1.5 on 2026-04-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
